server:  
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,application/json
    min-response-size: 1024

viet:
  child1: 123

logging:
  file: C:\log.txt

spring:
  cache:
    jcache:
      config:
        ehcache3.xml
  jackson:
    serialization:
      INDENT_OUTPUT: true