server:  
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,application/json

database:
  code: WIKI
  url: https://www.quandl.com/api/v3/datasets/%s/%s.json

logging:
  file: C:\log.txt

spring:
  cache:
    jcache:
      config:
        ehcache3.xml
  jackson:
    serialization:
      INDENT_OUTPUT: true